### ISSUE TITLE
Ensure that the new `platform` command has precedence over the legacy PHP one

### ISSUE THREAD

**Issue by lolautruche** [platformsh/homebrew-tap#1]
The legacy PHP installer installs the `platform` command in `$HOME/.platform/bin`, which usually has precedence over regular bin dirs in the `$PATH`, and more specifically over the one in the Homebrew prefix.

Could the formula ensure that the phar file is removed, or at least renamed?

**Comment by akalipetis** [comment]
The formulate cannot do that, for the same reasons that #3 is not possible.

Unfortunately, we don't have any way of doing that automatically, as `PATH` will always contain the legacy CLI first (or at least most of the times).

We might need to do this in coordination with a Legacy CLI release that can search if the new CLI is installed and prompt the user to do the switch.

What do you think @pjcdawkins? Any ideas are more than welcome!

**Comment by pjcdawkins** [comment]
> We might need to do this in coordination with a Legacy CLI release that can search if the new CLI is installed and prompt the user to do the switch.

I agree with that - I think there's a coordination plan needed here, what the legacy CLI can do when you run `platform up`, when you view release notes on upgrading, when you run the installer or `self:install`, etc. - whether or not the new wrapper is installed.

**Comment by akalipetis** [comment]
Totally agree, let me wrap my head around this a bit and I'll get back here. I can imagine that we could potentially use something like `PLATFORMSH_CLI_WRAPPED=true`, but we will still need a way to work our way through installations with both the legacy and the new CLI are installed and the legacy one has precedence over the new one.

**Comment by akalipetis** [comment]
@lolautruche I think we can now close this one, after the steps we took for migrating the Legacy CLI to the new installer.

**Comment by lolautruche** [comment]
You're right, thanks
