### ISSUE TITLE
Run `platform self:install` as part of the install formula

### ISSUE THREAD

**Issue by lolautruche** [platformsh/homebrew-tap#3]
`self:install` installs all needed helpers and code completion scripts, having it part of the formula seems to be needed in order to get a full installation.

```
platform self:install --no
```

The `--no` would avoid writing in the profile script on behalf of the user, and instead display:

```
To set up the CLI, add the following lines to: /Users/lolautruche/.bash_profile
# BEGIN SNIPPET: Platform.sh CLI configuration
HOME=${HOME:-'/Users/lolautruche'}
export PATH="$HOME/"'.platformsh/bin':"$PATH"
if [ -f "$HOME/"'.platformsh/shell-config.rc' ]; then . "$HOME/"'.platformsh/shell-config.rc'; fi # END SNIPPET
```

The `$PATH` line should however be removed.

**Comment by akalipetis** [comment]
Unfortunately this is not doable as part of the Homebrew formula installation. The Homebrew formula installation is run within a sandbox[^1] and thus cannot alter the user directory - which is what the `self:install` command does.

[^1]: https://docs.brew.sh/Formula-Cookbook#check-the-build-system
