### ISSUE TITLE
Post-install message regarding completion is misleading

### ISSUE THREAD

**Issue by lolautruche** [platformsh/homebrew-tap#6]
When installing v4.0-beta5 using Homebrew, the new message about autocompletion is confusing:

```
In order to enable completions, you need to follow one of the following steps:

  * Install using Homebrew and include bash-completion or zsh-completion package, depending on your shell of choice
  * Run the following command to enable completion for bash
    `echo 'echo 'eval $(platform completion bash)' >> ~/.bashrc'
  * Run the following command to enable completion for zsh
    `echo 'echo 'eval $(platform completion zsh)' >> ~/.zshrc'

Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
```

The command that is suggested to run is:
```
`echo 'echo 'eval $(platform completion bash)' >> ~/.bashrc'
```

When I try to launch it, it hangs like if I was missing a quote:

```
pythagore [13:59:27]:~$ echo 'echo 'eval $(platform completion bash)' >> ~/.profile
> 
```

So instead, I tried to manually edit my `.profile` by adding `echo 'eval $(platform completion bash)'`, but sourcing only displayed `eval $(platform completion bash)`.

I finally added `eval $(platform completion bash)` to my `.profile` and it worked after sourcing.

**Comment by akalipetis** [comment]
Fixed in `4.0.0-beta.6`
