### ISSUE TITLE
platform@5.0.19: hash check failed

### ISSUE THREAD

**Issue by Ste-wart** [platformsh/homebrew-tap#7]
Installing 'platform' (5.0.19) [64bit] from 'platformsh' bucket
platform_5.0.19_windows_amd64.zip (36.3 MB) [===============================>                                                                                 ]  28%
Checking hash of platform_5.0.19_windows_amd64.zip ... ERROR Hash check failed!
App:         platformsh/platform
URL:         https://github.com/platformsh/cli/releases/download/5.0.19/platform_5.0.19_windows_amd64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    58fd72ce3aa129bdfceae1fb02bc9b3c15130fb1cca97ca4cbb92c386fbb04ab
Actual:      712e6aa4826dc69fc02c5e6ab3bbf8a7d211edcf8e51767356dbbd22d658736e

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/platformsh/homebrew-tap/issues/new?title=platform%405.0.19%3a+hash+check+failed

**Comment by akalipetis** [comment]
Hey! We have released a new version of the CLI, which should fix this and another issue related to PHP in some systems. Can you please confirm everything is OK for you?
